# Generated by Django 4.2 on 2024-03-24 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='uploade_on',
        ),
        migrations.AddField(
            model_name='blogs',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
